version: '3.8'

services:
  database:
    image: postgres:13.11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper
  gateway-api:
#    container_name: gateway
    image: library-poc/gateway:latest
    build:
      context: ../gateway/gateway-api/
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "27060:7060"
    environment:
#      DATABASE_HOST: database
#      DATABASE_PORT: 5432
#      DATABASE_NAME: postgres
#      DATABASE_USER: postgres
#      DATABASE_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      default:
        aliases:
          - Library-Gateway
    depends_on:
      - kafka
  user-hub:
    restart: always
#    container_name: user-hub
    image: library-poc/user-hub:latest
    build:
      context: ../user-hub/
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "28060:8060"
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: user_service
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - database
      - kafka
  book-hub:
    restart: always
#    container_name: book-hub
    image: library-poc/book-hub:latest
    build:
      context: ../book-hub/
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "29060:9060"
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: book_service
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - database
      - kafka
  library-core:
#    container_name: library
    image: library-poc/library-core:latest
    build:
      context: ../library-core/
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "39060:19060"
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: library_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - database
      - kafka
